### ISSUE TITLE
Remove `pip-compile` requirement for lockfile generation

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#1104]
`pip-compile` is used as a lockfile generator for a few reasons:

1. It creates a `requirements.txt` file, which we already know how to parse
2. It supports a wide array of Python projects

However, most developers will not have `pip-tools` installed. So it isn't a great tool to rely on.

As of v23.0.0, `pip` has stabilized an [installation report][1] to resolve the exact dependencies that are installed when `pip install` is run. The [documentation][2] notes the usefulness of this to resolve dependencies:

> The install command has a `--report` option that will generate a JSON report of what pip has installed. In combination with the `--dry-run` and `--ignore-installed` it can be used to resolve a set of requirements without actually installing them.

[1]: https://pip.pypa.io/en/stable/reference/installation-report/
[2]: https://pip.pypa.io/en/stable/cli/pip_install/#obtaining-information-about-what-was-installed

The only missing piece here is our ability to parse this report.

**Comment by maxrake** [comment]
IIRC (will try to find references later)...the last time I looked into these options, it was discovered that the "resolve a set of requirements without actually installing them" language is a bit mis-leading. It may not _install_ the requirements in the traditional sense where they are left available in the environment, but packages are _downloaded_ and _built_ in order to acquire the metadata needed to fully resolve dependencies. Bottom line...arbitrary code can run and so #1103 is important here.

**Comment by kylewillmon** [comment]
> packages are _downloaded_ and _built_ in order to acquire the metadata needed to fully resolve dependencies

This behavior is required to support sdists. And is going to be a concern for **any** Python lockfile generator (including `pipenv`, `pip-tools`, `poetry`, `pip`, and any others that we may add in the future).

But that also means that it's irrelevant for this ticket. The concern will be addressed in #1103 (and possibly #1094)
