### ISSUE TITLE
Parallelize CI

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#1155]
Currently our CI is relatively slow and frequently running into disk space limitations. Part of the reason for this is that all CI steps run as a single workflow in series.

It's probably worth a try to separate independent CI steps into separate workflows, which should require less disk space individually and allow us to run more tasks in parallel to hopefully speed up CI.

**Comment by maxrake** [comment]
Current run times for the `Test` workflow's most intensive `test-matrix` job steps on the `ubuntu-20.04` runner:

* Build - 7m0s
* Clippy - 4m17s
* Test - 5m32s
* Oldstable - 6m58s
* All Features - 1m59s
* (The other steps have negligible run times)

It doesn't seem like these steps are required to happen serially...but maybe there was a good reason for that.

> It's probably worth a try to separate independent CI steps into separate workflows

Instead of separate _workflows_, these time intensive steps would likely fit better as separate _jobs_, but still within the `Test` workflow.
