### ISSUE TITLE
Update Available message language

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#125]
**Describe the issue**
The Update Available message does not take into consideration pre-release versions.

![image](https://user-images.githubusercontent.com/34108612/137179860-62bd4381-d0d2-48ec-8cc5-5c8fbf3db577.png)

**Describe the proposed solution**
We could possibly change the language to side-step this.  Proposed language:

You are not running the latest stable version of the Phylum CLI.
`phylum update`
The above command will update to the latest stable release.

I am not sure if we should also change the title to "Warning" or something like some other Linux CLI tools do?
![image](https://user-images.githubusercontent.com/34108612/137181178-4a5682ef-2a0c-4ec6-8956-5504bc7d9fe5.png)

**Estimated Subtasks**
TBD

**Comment by louislang** [comment]
Check for `-rc` in the version and indicate that the user is not on a stable version.

**Comment by kylewillmon** [comment]
It looks like the issue @furi0us333 noticed was caused by the workflow at the time.

During development of `v1.1.3`, the version was bumped on [Sep 27](https://github.com/phylum-dev/cli/commit/2d4bf8968ad20b90e05094a4d2d0fe933075465f), but the release and tag did not occur until almost a month later on [Oct 22](https://github.com/phylum-dev/cli/releases/tag/v1.1.3). This left a large gap of time (and a few prereleases) where the latest build version did not match the latest release version, so the update message was triggered and this "upgrade" became a downgrade.

Using our current workflow, the version bump and tag occur at the same time, so this gap does not exist and the observed behavior will not occur. Even if we ever have a failed release or something else that might cause this gap in the future, we can avoid this issue by reverting the cargo version.
