### ISSUE TITLE
Update CLI to use new Request manager support in API

### ISSUE THREAD

**Issue by DanielJoyce** [phylum-dev/cli#131]
Ensure the CLI is kept in sync with the new Request Manager API

**Comment by louislang** [comment]
As we deprecate request manager behind the scenes, we'll need to make the corresponding updates to the CLI to ensure that we are hitting the proper endpoints.

**Comment by kylewillmon** [comment]
This issue seems far too broad to me. Updating the CLI as the API changes is just a part of normal development.

I am closing this issue. If there are concrete API changes that we want to track, such as the deprecation of request manager, that can be done in a new issue that includes concrete details such as what API endpoints we need to avoid, etc.
