### ISSUE TITLE
Allow linking projects to groups

### ISSUE THREAD

**Issue by cd-work** [phylum-dev/cli#276]
# Overview

Users should be able to link projects with a group specified:

```
phylum projects link --group <GroupID> <ProjectName>
```

This should then link the current repository to the specified project owned by the specified group. If group is not specified, `phylum projects link` should always linke against user projects and ignore group projects. If it is specified, it should never link against user projects.

Similar to #144 (comment), it might be nice to consider using the group name, rather than the ID. However that is likely better suited for a follow-up.

# Acceptance Criteria
- [ ] With the `--group` flag, the project from the specified group is linked to the repository
- [ ] Without the `--group` flag, the user's projects are used for linking even if a group project with the same name exists

## Associated User Story
https://www.notion.so/phylum/Update-CLI-to-Support-Group-b4b3c5affde54d63a23bfbf8faad9232

**Comment by kylewillmon** [comment]
Just confirming here: The only time that this would be necessary is if there is a name conflict between one of the user's project and a project owned by a group that the user is a member of. Is that correct?

That seems like a pretty rare occurrence... Even more rare when you consider that most projects will never need the `link` command since they'll just use `create` and commit the `.phylum_project` file.

**Comment by cd-work** [comment]
> Just confirming here: The only time that this would be necessary is if there is a name conflict between one of the user's projects and a project owned by a group that the user is a member of. Is that correct?

Based on my discussion with @louislang, that is incorrect. The `--group` flag should **always** be passed when the project is owned by one of your groups rather than your own.
