### ISSUE TITLE
Remove `project` subcommand from `ph history`

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#277]
# Overview
The `phylum history` command includes a `project` subcommand which feels out of place. We should remove the functionality from this location and users should leverage `phylum project` or `phylum project list` to acquire the same output.

# Expected Behavior
The `phylum history` command does not include a `project` subcommand.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/164060667-68d4832a-279f-401f-9a23-46f64eff1873.png)

**Comment by kylewillmon** [comment]
That command definitely needs some better documentation and maybe needs to be reworked... But it's got some useful functionality. Here are the ways to run it:

1. `phylum history project` -> Lists projects (duplicate of `phylum project`)
2. `phylum history project <project_name>` -> List jobs for a project
3. `phylum history project <project_name> <job_id>` -> Show job results (duplicate of `phylum history <job_id>`)

As you point out, case 1 is useless. Also, case 3 is useless (see my random shenanigans below). Case 2 is where this gets complicated.

## Listing historical jobs for a project

The one case where `phylum history project` is actually useful is the `<project_name>` form. As far as I can tell, this is the only place to list historical jobs for a project. For example:

```
❯ ph history project test-project
  Project Name: test-project                                       Project ID: b2370c8c-2b8e-4f3e-9a67-83c39c3beb28
     Ecosystem: unknown

    Thresholds: Score requirements to PASS or FAIL a run. Runs that have a score below the threshold value will FAIL.
           Project Score: 60
 Malicious Code Risk MAL: Not Set
  Vulnerability Risk VLN: Not Set
    Engineering Risk ENG: Not Set
         Author Risk AUT: Not Set
        License Risk LIC: Not Set

Last 2 jobs from project history
Score  P/F        Label                                    Job ID                                 Datetime
100    PASS       uncategorized                            6a5e9bc2-2342-4e73-8328-c5e969139dae   2022-04-20T18:43:52.736667Z
100    PASS       uncategorized                            432acb43-46fc-46ba-93ea-ab4c520b227b   2022-04-20T18:43:54.916665Z
```

Weirdly, this is also the only place in the CLI where you can retrieve the thresholds that have been set for a project. That feels pretty unnatural.

It definitely makes sense to keep this functionality, but maybe we should move it somewhere else. There are two options that I think make sense:

### Option 1

The simple solution is to add a `--project <project_name>` option to the `phylum history` command. Since that command lists jobs, a `--project <project_name>` option to limit the job listing to specific project seems natural. We could then completely remove the `phylum history project` subcommand (or subsubcommand, I guess?)

### Option 2

The output here is a lot of details about the project and not just a job listing. So perhaps this feature would make more sense to be run as `phylum project show <project_name>`.

## Does the `history` subcommand even make sense?

One additional thought: The entire point of the `history` subcommand is to show information about jobs. It would seem more natural to expose this as `phylum job`

### Random shenanigans

The `phylum history project <project_name> <job_id>` command completely ignores the project name. There is no requirement that `<job_id>` actually be a job in `<project_name>`, and it doesn't even have to be an existing or valid project name:

```
❯ phylum history project 💩 6a5e9bc2-2342-4e73-8328-c5e969139dae
                                                                                                                                                      
                                                                                                                                                      
          Project: test-project                                            Label: uncategorized                                                       
       Proj Score: 100                                                      Date: 2022-04-20 18:43:52 UTC                                             
         Num Deps: 4                                                      Job ID: 6a5e9bc2-2342-4e73-8328-c5e969139dae                                
          User ID: kyle@phylum.io                              View in Phylum UI: https://app.phylum.io/projects/b2370c8c-2b8e-4f3e-9a67-83c39c3beb28 
        Ecosystem: NPM                                                                                                                                
                                                                                                                                                      
     Score       Count                                                                                                                                
     91 - 100  [    4] ████████████████████████████████████████████████████████                        Thresholds:                                    
     81 - 90   [    0]                                                                              Project Score: 60                                 
     71 - 80   [    0]                                                                    Malicious Code Risk MAL:  0                                 
     61 - 70   [    0]                                                                     Vulnerability Risk VLN:  0                                 
     51 - 60   [    0]                                                                       Engineering Risk ENG:  0                                 
     41 - 50   [    0]                                                                            Author Risk AUT:  0                                 
     31 - 40   [    0]                                                                           License Risk LIC:  0                                 
     21 - 30   [    0]                                                                                                                                
     11 - 20   [    0]                                                                                                                                
      0 - 10   [    0]                                                                                                                                
                                                                                                                                                      
           Status: PASS                                                                                                                               
```
