### ISSUE TITLE
`phylum extension check` subcommand

### ISSUE THREAD

**Issue by andreaphylum** [phylum-dev/cli#328]
# Overview
Subcommand to check that a given extension exists. To be exposed for other extensions to use.

# Acceptance Criteria
- [ ] An extension can run `phylum extension check <extensionName>` to check if another extension is installed before calling that other extension.

## Associated User Story
https://www.notion.so/phylum/Extension-Base-CLI-Capability-bff6fcf7c0c947b79b8c49a928f59cc4

**Comment by andreaphylum** [comment]
Note: the extension should probably both output a string value and set an appropriate exit code.

**Comment by cd-work** [comment]
@kylewillmon I didn't find it in the Notion user story, but did you question whether this was necessary at all, or was that someone else?

I'd like to bring this up again since I'm not sure this is necessary for the MVP. Extensions depending on each other is something that I'd argue comes with a lot of risks, so it's probably best to approach it with some caution?

**Comment by kylewillmon** [comment]
> I'd like to bring this up again since I'm not sure this is necessary for the MVP. Extensions depending on each other is something that I'd argue comes with a lot of risks, so it's probably best to approach it with some caution?

I think it was someone else that brought it up initially. But I agree. This should be probably be removed from MVP.

**Comment by kylewillmon** [comment]
With no objections, I am closing this issue and considering it removed from MVP
