### ISSUE TITLE
CLI Integration tests

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#429]
The CLI needs integration tests to confirm the functionality of our tool over time. To start, these can test some basic functionality, but we can add more over time.

# Acceptance Criteria
- [ ] Integration tests are run in CI
- [ ] The API URL and token are configurable (to allow running against prod, staging, or localdev)
- [ ] The tests do not run by default when running `cargo test`
- [ ] The tests do not use the installed `settings.yaml`

**Comment by andreaphylum** [comment]
Pertaining to PR #490 and issue #444: we need coverage over the borrows-related code, specifically to ensure that no concurrency issues are happening (deadlocks).

A test for that would hit the network and provide significant latency, so it is better suited in the form of an integration test.

The implementation would create a number of un-awaited futures in an extension, and await on them all together via `Promise.all()` in order to generate contention.

Leaving this comment here in order to remember to add coverage on that front once we have support for integration tests.
