### ISSUE TITLE
Simplify error messages

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#473]
# Overview
The error messages displayed by the CLI are not very user-friendly and should be simplified and more direct.

# How To Reproduce
Steps to reproduce this behavior:
1. Take an action that generates an error (e.g., try and create a project that already exists)
2. See error messaging

# Expected Behavior
A clear and concise error message is displayed to the user, not JSON.

# Additional Context
![image](https://user-images.githubusercontent.com/34108612/174204072-8f78d952-a84b-4bdd-8d74-249a77ea8d87.png)

**Comment by louislang** [comment]
The errors used to be much more verbose than this. After deprecating the request manager, we normalized error messages coming back from the API. Some cleanup work was done around the DAOs. We should just update the CLI to parse the returned JSON, and provide a more meaningful response to the user (e.g., `A project with that name already exists`).

**Comment by kylewillmon** [comment]
Alright. So I see 3 separate issues here:

1. The error message is printed twice
2. The error message contains raw JSON
3. The error description is unhelpful

Problems 1 and 2 can be fixed by CLI. After fixing those, I would expect the output to look like this:

```
> phylum project create foo
❗ Could not create project 'foo': resource conflict, resource already exists under the given identifier
```

Solving problem 3 is going to require some help from API since that description (`"resource conflict..."`) is coming from their code.

### A note about logging

The additional information is still useful in certain situations. In particular, the `error_id` helps to match this error to the same error in the server logs. We should definitely retain the ability to show these details (i.e., by setting `RUST_LOG` or using a `-v` flag), but maybe not by default.

**Comment by cd-work** [comment]
> The error message contains raw JSON

While common errors shoudln't rely on this, I definitely prefer raw JSON over opaque errors. So we should likely selectively pick errors we recognize and transform them into nicer messages.

> The error message is printed twice

It's probably good to look into fixing this even for scenarios where we want to include raw JSON.
