### ISSUE TITLE
Add a `--check-certificate` command line option

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#483]
If the user sets `ignore_certs` in their config file, there is currently no way to force the CLI to check certificates without modifying that file.

**Comment by cd-work** [comment]
While this makes sense in theory, I wonder how relevant it would be in practice? If you send so much stuff without certificates that you even set it in your config file, do you really have the need to manually send stuff with certificates in one-off requests?

**Comment by cd-work** [comment]
I'm going to close this issue because I think this would just make the CLI worse by adding a CLI option that doesn't really have a purpose.

I've contemplated just adding `--ignore-certs false` as some kind of optional argument to the flag, but really any way to implement this would just be done because it's easy, not because it's a good feature.

Ultimately if you're frequently running both with and without certificate checks, then an alias is probably what you want. And if you're always running without certs, checking certificates that *one* time doesn't really seem necessary.

If there's a request by customers in the future I'm happy to reconsider, but at this point this mostly just seems like the feature request exists because it would be easy, not because it's a good feature.
