### ISSUE TITLE
Confusing results of argument ordering

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#555]
Our use of subcommands means that arguments are parsed differently at different levels. And often, arguments at a higher level are completely ignored, which can lead to confusing situations.

## Example 1: Listing projects
The results of `phylum project list --group foo` are different than `phylum project --group foo list`:

```
❯ phylum project list --group x
Project Name                 Project ID
foo                          b0f27770-ff5e-46f3-a53d-afac51e52308

❯ phylum project --group x list
Project Name                 Project ID
bar                          71ad1d65-ebe9-4c9f-a435-def73cf36fcc
```

## Example 2: Creating a project

First, I list the projects in a group:
```
❯ phylum project --group x
Project Name                 Project ID
foo                          b0f27770-ff5e-46f3-a53d-afac51e52308
```

Then I attempt to add a project. For simplicity, I just hit the up arrow and type `create bar` onto the end of the last command:
```
❯ phylum project --group x create bar
✅ Successfully created new project, bar
```

Somewhat confusingly, this did not create a new project in that group:
```
❯ phylum project --group x           
Project Name                 Project ID
foo                          b0f27770-ff5e-46f3-a53d-afac51e52308
```

**Comment by cd-work** [comment]
Would you suggest just manually going through all parameter instances where three are duplicate parameters on parent and child subcommand and picking whatever is available?

What about `phylum project --group x list --group y`? Should that be an error? Should the last specified group be used? The first?

I personally don't think a manual solution is particularly maintainable/sustainable, so I'd advocate for something a little easier to support. If possible, I'd maybe setup all the flags in the `project` subcommand to conflict with the child subcommands? That way you cannot specify groups at the project level.

I personally think that approach would make most sense, having flags in multiple places is a recipe for disaster so it should be forced to be used in one specific place. And having it on the last level really is the only thing that makes sense, since that's what users are interacting with and will get docs about with `--help` and stuff.

**Comment by cd-work** [comment]
An alternative would be to rework the CLI and nuke all commands that can be used on their own while also having subcommands. So `phylum project` becomes invalid and `phylum project list` will be the only way to do this. That would certainly make things easier to reason about.

**Comment by kylewillmon** [comment]
> I'd maybe setup all the flags in the project subcommand to conflict with the child subcommands?

:+1: This could work

> An alternative would be to rework the CLI and nuke all commands that can be used on their own while also having subcommands.

:+1: This could also work. I slightly prefer the other option because `phylum project` is a convenient shortcut that I do personally use. But I can live with either.

In either solution, `phylum project --group x create foo` becomes invalid and I think that's fine.
