### ISSUE TITLE
`PhylumApi.runSanboxed` does not sandbox environment variables

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#703]
The `runSandboxed` API allows access to environment variables that Deno would otherwise restrict.

In the example below, you can see that `bash` has access to the `SECRET` environment variable when `PhylumApi.runSanboxed()` is used even with extremely limited permissions, but does not have access to that variable when a basic `Deno.run()` is used.

# POC extension
```ts
import { PhylumApi } from "phylum"

console.log("== Sandboxed ==");
PhylumApi.runSandboxed({
    cmd: 'bash',
    args: ['-c', 'echo $SECRET'],
    exceptions: {
        write: false,
        run: false,
        read: false,
        net: false,
    },
});

console.log("== Not Sanboxed ==");
Deno.run({cmd: ['bash', '-c', 'echo $SECRET']});
```

# POC output
```
❯ SECRET=ThisIsMySecret phylum extension run -y ./extensions/escape
== Sandboxed ==
ThisIsMySecret
== Not Sanboxed ==
```

Credit to @louislang for reminding me to test this...

**Comment by louislang** [comment]
> We cannot rely on `landlock` or `seccomp` for this, as the environment is not accessed via syscalls but rather lives in the [process' memory itself](https://man7.org/linux/man-pages/man7/environ.7.html).
> 
> A potentially viable solution for this would be to pass a custom-filtered environment to the [child process](https://man7.org/linux/man-pages/man2/execve.2.html) but we need to address platform-dependent caveats, like the fact that the `char** envp` argument to C runtime's `main` is non-POSIX.

Yeah, I think it'd be nice to limit access to env vars, but probably not strictly necessary as a first pass feature. Even if someone can read a secret from the environment, they can't ship that off to a remote service due to the network sandbox.

**Comment by cd-work** [comment]
I intentionally left out environment variable as a sandboxing rule due to landlock/seccomp limitations in this area, while also missing a viable attack vector when executing extensions on a user's system.

Generally I don't expect environment variables to contain important secret information when running extensions interactively, since that would be somewhat of a strange security practice to begin with.

I'd assume the main concern here is when executing extensions in the CI environment, where important secrets like API keys might be present through environment variables?

**Comment by louislang** [comment]
> I'd assume the main concern here is when executing extensions in the CI environment, where important secrets like API keys might be present through environment variables?

This exactly. Though I could see a dev having `AWS_SECRET_KEY` or similar in their local environment as well. We've seen malware explicitly looking for this. But I think it's not a huge concern right this second, if they do grab the environment variables, they can't send them anywhere due to the networking sandbox.

**Comment by kylewillmon** [comment]
> Even if someone can read a secret from the environment, they can't ship that off to a remote service due to the network sandbox.

I think this may be answered by another comment here:

> I'd assume the main concern here is when executing extensions in the CI environment

In a CI environment, exporting the secret may be as simple as printing it to `stdout` because that will be logged.

So the attack vector here is that an attacker might release a malicious install script that does nothing more than print secrets to `stdout` in the hopes of scraping secrets from the CI logs of open source projects.
