### ISSUE TITLE
Proposal: Version the extension API

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#988]
__Note__: This proposal is still a work in progress. This description will be updated as the idea evolves.

As we are likely to introduce breaking changes, the extension API needs versioning. To do this, we can add a `target_version` field to the `PhylumExt.toml` file.

```toml
name = "some-ext"
description = "Some extension"
entry_point = "main.ts"
target_version = 1
```

When loading extensions, the CLI will load the appropriate internal Phylum extension module to match the requested `target_version`. The CLI will error if the requested target version is not supported, and may emit a warning if the requested target version is deprecated.

### How often will we release new versions?

I would expect a new version of the extension API every 3-6 months during initial development. As the product matures, that should slow down and eventually a stable API will be reached.

### Development of new versions

While the next target version is in development, we can document it as "unstable" or "under development" before officially releasing it. This will allow us to batch together breaking changes and only release them when we are ready.

### Testing

Ideally, we should test the latest CLI against the oldest extension that it supports and the latest extensions against the oldest CLI that supports them. Setting up this system may require some effort.

**Comment by cd-work** [comment]
> I would expect a new version of the extension API every 3-6 months during initial development. As the product matures, that should slow down and eventually a stable API will be reached.

I don't think we should nail down a specific release cycle for new versions. Our extension API doesn't get regular updates in the first place so I don't think we can make *any* sort of statement about how often we expect to break it (even historically it hasn't been consistent).

`target_version` as a name is also a bit unfortunate to me. The `target` here doesn't really say anything useful, considering that it's just the API version and the `target` prefix isn't just a "rough goal" but it's always going to be that exact version.

I also don't think the version should be specified in the manifest file. I'd say loading the different phylum modules should be based on import paths. It should be easy to support multiple versions in the same extension, we'd probably just load them all into our runtime anyway.

I'm also not entirely sure how a versioned API module will help with breaking changes. Ultimately the breaking changes are usually happening in our interface between JavaScript and Rust and in the past we've broken the API because backend changes meant the existing API was not matching our backend anymore.

**Comment by kylewillmon** [comment]
The extension API has stabilized over the last few months, which has helped this be less of an issue.

We can revisit versioning if/when the REST API bumps their version from v0 (to v1 and beyond). Until then, it is understandable that our API will change with theirs.
